### PR TITLE
Add blockOnAuthenticationFailureMaxRetry

### PR DESCRIPTION
**Pull request by arpesenti**
This is to add the blockOnAuthenticationFailureMaxRetry option to specify after how many failed authentications a subsequent request from the same address should be blocked.

### CODE REVIEW

**Review by rfm — COMMENTED** [review]
This looks good, particularly the test!
One observation about performance though;  The use of a mutable dictionary containing NSNumber objects to implement incrementing counters is quite inefficient (every request would create a new NSNumber and destroy an old one).  Given that each request does a *lot* of other stuff, that inefficiency is probably never significant, but using an NSCountedSet would be both faster and a little simpler.

**Comment by arpesenti** [comment]
Yes, using a NSCountedSet would make much more sense. Thanks for the suggestion, I’ll prepare the change.

**Comment by arpesenti** [comment]
I have just realised that using a NSCountedSet makes removing an address from the set a bit ugly: my understanding is that [NSCountedSet removeObject:] just decreases the count for an object and there is not a way to remove an object altogether, independently of the count, other than calling [NSCountedSet removeObject:] in a loop. 

Maybe I should encapsulate the failure information (timestamp and count) in a simple mutable class and just keep one NSMutableDictionary keyed on the address.

**Comment by arpesenti** [comment]
I have encapsulated the authentication failure information into the WebServerAuthenticationFailure class and the lookup by address and locking is now done in the WebServerAuthenticationFailureLog class. 

I've also come to realize that an authentication failure record was only deleted when a new request from the same IP was received. If no such request arrived, we would unintentionally retain the WebServerAuthenticationFailure object forever. To address this issue, I've introduced a periodic cleanup method.

**Comment by arpesenti** [comment]
I have changed the code to look for failures in a window of time rather than to a sequence of failures. The parameters are:
- authenticationFailureBanTime: how many seconds an IP should be blocked for
- authenticationFailureMaxRetry: number of failed authentications in the specified find time window for an IP to be blocked
- authenticationFailureFindTime: window of time to look for failed authentications

The performance impact for the happy path (i.e. all authenticated requests) should be pretty minimal. If there are unauthenticated requests from an IP then we need to loop over each failure that was recorded in the specified timeframe.

**Review by rfm — APPROVED** [review]

**Pull request merged**
